---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  qtest:
    - dependency
    - create
    - prepare
    - converge
    - destroy